artifact_location: file:c:/Users/Hp/Desktop/Projects/10Academy/credit-risk-model/notebooks/YOUR_TRACKING_URI_HERE/0
creation_time: 1780491256146
effective_trace_archival_retention: null
experiment_id: '0'
last_update_time: 1780491256146
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
