artifact_location: file:c:/Users/Hp/Desktop/Projects/10Academy/credit-risk-model/notebooks/YOUR_TRACKING_URI_HERE/487194884048966721
creation_time: 1780491447986
effective_trace_archival_retention: null
experiment_id: '487194884048966721'
last_update_time: 1780491447986
lifecycle_stage: active
name: credit-risk
trace_location: null
workspace: default
