artifact_uri: file:c:/Users/Hp/Desktop/Projects/10Academy/credit-risk-model/notebooks/YOUR_TRACKING_URI_HERE/487194884048966721/38f141afe85543999f1d5edd4b03f2c7/artifacts
end_time: 1780491448029
entry_point_name: ''
experiment_id: '487194884048966721'
lifecycle_stage: active
run_id: 38f141afe85543999f1d5edd4b03f2c7
run_name: respected-robin-629
source_name: ''
source_type: 4
source_version: ''
start_time: 1780491447999
status: 4
tags: []
user_id: Hp
