artifact_uri: file:c:/Users/Hp/Desktop/Projects/10Academy/credit-risk-model/notebooks/YOUR_TRACKING_URI_HERE/487194884048966721/372f1bd16fd9438b98a2b2ca9537d4c6/artifacts
end_time: 1780492131838
entry_point_name: ''
experiment_id: '487194884048966721'
lifecycle_stage: active
run_id: 372f1bd16fd9438b98a2b2ca9537d4c6
run_name: rare-bee-827
source_name: ''
source_type: 4
source_version: ''
start_time: 1780492123721
status: 3
tags: []
user_id: Hp
